[package]
name = "monitor-color-extraction"
version = "0.1.0"
edition = "2021"
 
[dependencies]
clap = { version = "4.4.11", features = ["derive"] } 
screenshots = "0.8.5"
image = "0.24.7"
rand = "0.8.5"
serde_json = "1.0.110"
serde = { version = "1.0.194", features = ["derive"] }
